get:
  x-eov-operation-id: find
  x-eov-operation-handler: v1/handlers/webhooks/webhooks.handler
  summary: Finds a webhook by method and path
  description: Finds a webhook by method and path
  parameters:
    - name: method
      in: query
      required: true
      description: The HTTP method of the webhook
      schema:
        type: string
    - name: path
      in: path
      description: The path of the webhook
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          type: object
          additionalProperties: true
          properties:
            webhookPath:
              type: string
            method:
              type: string
            workflowId:
              type: string
            node:
              type: string
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
    '500':
      description: Internal server error.
